pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  outDir: $(Build.ArtifactStagingDirectory)

steps:
- script: dotnet build --configuration $(buildConfiguration) --output $(outDir) /bl:$(outDir)/msbuild.binlog
  displayName: 'dotnet build $(buildConfiguration)'
- task: PublishBuildArtifacts@1
